### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by blokhin** [basf/svelte-spectre#108]
```
# npm run test

> svelte-spectre@0.4.12 test
> uvu tests '.spec.ts' -r tsm -r tests/setup/register -i setup

Error: Cannot find module "tests/setup/register"
    at /home/eb/svelte-spectre/node_modules/uvu/parse/index.js:22:21
    at Array.forEach (<anonymous>)
    at parse (/home/eb/svelte-spectre/node_modules/uvu/parse/index.js:20:11)
    at /home/eb/svelte-spectre/node_modules/uvu/bin.js:23:20
    at o.parse (/home/eb/svelte-spectre/node_modules/sade/lib/index.js:1:3402)
    at Object.<anonymous> (/home/eb/svelte-spectre/node_modules/uvu/bin.js:35:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```

**Comment by blokhin** [comment]
@GlistenSTAR do you have an idea?

**Comment by GlistenSTAR** [comment]
Hello, @blokhin 
I have no idea for this.

**Comment by blokhin** [comment]
@luckylionheart would be great to fix this 😢
